language: minimal

services:
  - docker

script:
  - 'docker run --rm -v "$(pwd):/go/src/github.com/Al2Klimov/check_autoremove" grandmaster/go-app-factory'

deploy:
  provider: releases
  api_key:
    secure: JFYSruV7qqK2YV5Foe+djVcb0mRq5lpiXVmY/uq2mPKtz8nY6vG0ahh/7AakAJNmGJ8s79Hz3BUKhqWACjxLvWFtATZj8lN16yAuVIYM1BmjNZQ9Vc3uVkNR0HlXdNev4Y94FOe7fjiMlt1jfsHTFJpw/vCdZn6zyYvJRau3z+a8EdVifPZIh6y6DrmEO2FKqRfuugayo5IH0vq5GLzY3sBFWH08sLzmKQ+V+EX8Kj8l6z7gylQaGAY9M/tyesDY1noIxFhgNrSmgrt12XJSiR1HAT2DKbrw/x8e0Uc1h3Fc+v3E4ygxN9dzNMbf1gMo1KtEYdMawCHaiUQnndZ06xGgTbn5yRZ0/I9hzBPBJTKoUlni/cfTTiVcdqI6LickAmqWlOiqgy1jRt3X5u4DtA6h63kg8fe4tNd4e7WMd8EtVQZHfHYE4QciytQbChzE+4Cfyf+YQrP6T8eRVURGiNZFXQmvfr8j16BYDjH0iPu1oD8+YqmnRtMinEBpQmksM3PIPSFYb9qsKEgrH4o7mFZSZWxq+BxRJsqssj7zdAto+1RpJriXsJr/gG+gQQoZA+uuAA0PWE4sOR9MtGhVCuRp9ZOFFhze+FZ6eY4lk4juvIHnuLeE2iygTFdrEUeT0lTEUGtyie1fk7CXYa89vzkxTFehefqgDBQ1kYCYNjc=
  file_glob: true
  file: check_*.*-*
  skip_cleanup: true
  on:
    tags: true
